#!/bin/bash

set -eu

hook_names=(
	applypatch-msg
	pre-applypatch
	post-applypatch
	pre-commit
	prepare-commit-msg
	commit-msg
	post-commit
	pre-rebase
	post-checkout
	post-merge
	pre-push
	pre-receive
	update
	post-receive
	post-update
	push-to-checkout
	pre-auto-gc
	post-rewrite
	sendemail-validate
	fsmonitor-watchman
	p4-pre-submit
)

cd $(dirname $0)

for hook_name in ${hook_names[@]}; do
	echo ${hook_name}
	ln -sf base ${hook_name}
done
