[tools]
usage = "latest"
clojure = "latest"
deno = "latest"
elixir = "latest"
erlang = "latest"
gauche = "latest"
ghc = "latest"
golang = "latest"
groovy = "latest"
java = "latest"
julia = "latest"
kotlin = "latest"
lua = "latest"
luajit = "latest"
nodejs = "latest"
ocaml = "latest"
perl = "latest"
php = "latest"
python = ["3", "2"]
racket = "latest"
rclone = "latest"
ruby = "latest"
rust = "latest"
scala = "latest"
zig = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = [
  "node",
  "ruby",
]
